from distutils.core import setup, Extension

module = Extension('devguard_carrier',
                   define_macros=[('MAJOR_VERSION', '0'),
                                  ('MINOR_VERSION', '1')],
                   sources=[
                       '/Users/simon/Sites/carrier/3rdparty/hacl-star/snapshots/hacl-c/FStar.c',
                       '/Users/simon/Sites/carrier/3rdparty/hacl-star/snapshots/hacl-c/kremlib.c',
                       '/Users/simon/Sites/carrier/3rdparty/hacl-star/snapshots/hacl-c/Hacl_Ed25519.c',
                       '/Users/simon/Sites/carrier/3rdparty/hacl-star/snapshots/hacl-c/Hacl_Curve25519.c',
                       '/Users/simon/Sites/carrier/3rdparty/hacl-star/snapshots/hacl-c/Hacl_SHA2_256.c',
                       '/Users/simon/Sites/carrier/3rdparty/hacl-star/snapshots/hacl-c/Hacl_HMAC_SHA2_256.c',
                       '/Users/simon/Sites/carrier/3rdparty/hacl-star/snapshots/hacl-c/Hacl_Chacha20Poly1305.c',
                       '/Users/simon/Sites/carrier/3rdparty/hacl-star/snapshots/hacl-c/Hacl_Chacha20.c',
                       '/Users/simon/Sites/carrier/3rdparty/hacl-star/snapshots/hacl-c/AEAD_Poly1305_64.c',
                       '/Users/simon/Sites/carrier/3rdparty/hacl-star/snapshots/hacl-c/Hacl_Policies.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier.c',
                       '/Users/simon/Sites/carrier/target/release/zz/symbols.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_config.c',
                       '/Users/simon/Sites/carrier/target/release/zz/pool.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_pub_sysinfo.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_sha256.c',
                       '/Users/simon/Sites/carrier/target/release/zz/net_udp.c',
                       '/Users/simon/Sites/carrier/target/release/zz/net_tcp.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_identity.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_pq.c',
                       '/Users/simon/Sites/carrier/target/release/zz/hex.c',
                       '/Users/simon/Sites/carrier/target/release/zz/sysinfo_proto.c',
                       '/Users/simon/Sites/carrier/target/release/zz/toml.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_bootstrap.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_router.c',
                       '/Users/simon/Sites/carrier/target/release/zz/slice_mut_slice.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_peering.c',
                       '/Users/simon/Sites/carrier/target/release/zz/byteorder.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_symmetric.c',
                       '/Users/simon/Sites/carrier/target/release/zz/err.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_endpoint.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_proto.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_initiator.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_connect.c',
                       '/Users/simon/Sites/carrier/target/release/zz/net_tcp_server.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_vault.c',
                       '/Users/simon/Sites/carrier/target/release/zz/log.c',
                       '/Users/simon/Sites/carrier/target/release/zz/net.c',
                       '/Users/simon/Sites/carrier/target/release/zz/io.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_cipher.c',
                       '/Users/simon/Sites/carrier/target/release/zz/time.c',
                       '/Users/simon/Sites/carrier/target/release/zz/mem.c',
                       '/Users/simon/Sites/carrier/target/release/zz/string.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_sync.c',
                       '/Users/simon/Sites/carrier/target/release/zz/sysinfo.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_crc8.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_channel.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_stream.c',
                       '/Users/simon/Sites/carrier/target/release/zz/fs.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_rand.c',
                       '/Users/simon/Sites/carrier/target/release/zz/net_address.c',
                       '/Users/simon/Sites/carrier/target/release/zz/slice_slice.c',
                       '/Users/simon/Sites/carrier/target/release/zz/hpack_decoder.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_vault_toml.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_noise.c',
                       '/Users/simon/Sites/carrier/target/release/zz/io_unix.c',
                       '/Users/simon/Sites/carrier/target/release/zz/hpack_encoder.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_sft.c',
                       '/Users/simon/Sites/carrier/target/release/zz/protonerf.c',
                       '/Users/simon/Sites/carrier/target/release/zz/hpack.c',
                       '/Users/simon/Sites/carrier/target/release/zz/slice.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_publish.c',
                       '/Users/simon/Sites/carrier/target/release/zz/carrier_responder.c',
                       '/Users/simon/Sites/carrier/src/base58.c',
                       '/Users/simon/Sites/carrier/target/release/gen/zz_builtins_carrier_carrier_CMake.c',
                       '/Users/simon/Sites/carrier/target/release/python/pycarrier.c',
                   ],
                   include_dirs=['release/include'],
                   libraries=['carrier'],
                   library_dirs=['release/lib/'])

setup(name='devguard_carrier',
      version='0.1',
      description='carrier python api',
      author='Arvid E. Picciani',
      author_email='arvid@devguard.io',
      url='https://github.com/devguardio/carrier-python',
      ext_modules=[module])
