// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.0
// source: carrier.discovery.v1.proto

package protos

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DiscoveryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CarrierRevision    uint32   `protobuf:"varint,1,opt,name=carrier_revision,json=carrierRevision,proto3" json:"carrier_revision,omitempty"`
	CarrierBuildId     string   `protobuf:"bytes,2,opt,name=carrier_build_id,json=carrierBuildId,proto3" json:"carrier_build_id,omitempty"`
	Application        string   `protobuf:"bytes,3,opt,name=application,proto3" json:"application,omitempty"`
	ApplicationVersion string   `protobuf:"bytes,4,opt,name=application_version,json=applicationVersion,proto3" json:"application_version,omitempty"`
	Paths              []string `protobuf:"bytes,5,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *DiscoveryResponse) Reset() {
	*x = DiscoveryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_carrier_discovery_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResponse) ProtoMessage() {}

func (x *DiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carrier_discovery_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_carrier_discovery_v1_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoveryResponse) GetCarrierRevision() uint32 {
	if x != nil {
		return x.CarrierRevision
	}
	return 0
}

func (x *DiscoveryResponse) GetCarrierBuildId() string {
	if x != nil {
		return x.CarrierBuildId
	}
	return ""
}

func (x *DiscoveryResponse) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *DiscoveryResponse) GetApplicationVersion() string {
	if x != nil {
		return x.ApplicationVersion
	}
	return ""
}

func (x *DiscoveryResponse) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

var File_carrier_discovery_v1_proto protoreflect.FileDescriptor

var file_carrier_discovery_v1_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x63, 0x61,
	0x72, 0x72, 0x69, 0x65, 0x72, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e,
	0x76, 0x31, 0x22, 0xd1, 0x01, 0x0a, 0x11, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x61, 0x72, 0x72,
	0x69, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0f, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x52, 0x65, 0x76, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x5f, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63,
	0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2f, 0x0a, 0x13, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_carrier_discovery_v1_proto_rawDescOnce sync.Once
	file_carrier_discovery_v1_proto_rawDescData = file_carrier_discovery_v1_proto_rawDesc
)

func file_carrier_discovery_v1_proto_rawDescGZIP() []byte {
	file_carrier_discovery_v1_proto_rawDescOnce.Do(func() {
		file_carrier_discovery_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_carrier_discovery_v1_proto_rawDescData)
	})
	return file_carrier_discovery_v1_proto_rawDescData
}

var file_carrier_discovery_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_carrier_discovery_v1_proto_goTypes = []interface{}{
	(*DiscoveryResponse)(nil), // 0: carrier.discovery.v1.DiscoveryResponse
}
var file_carrier_discovery_v1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_carrier_discovery_v1_proto_init() }
func file_carrier_discovery_v1_proto_init() {
	if File_carrier_discovery_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_carrier_discovery_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoveryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_carrier_discovery_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_carrier_discovery_v1_proto_goTypes,
		DependencyIndexes: file_carrier_discovery_v1_proto_depIdxs,
		MessageInfos:      file_carrier_discovery_v1_proto_msgTypes,
	}.Build()
	File_carrier_discovery_v1_proto = out.File
	file_carrier_discovery_v1_proto_rawDesc = nil
	file_carrier_discovery_v1_proto_goTypes = nil
	file_carrier_discovery_v1_proto_depIdxs = nil
}
